[projectprac.fun]
34.229.10.211 ansible_user=ec2-user ansible_password=DevOps321
[mongodb.projectprac.fun]
98.93.55.55 ansible_user=ec2-user ansible_password=DevOps321
[catalogue.projectprac.fun]
34.229.10.211 ansible_user=ec2-user ansible_password=DevOps321